// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCT_DzOXrc13yux8rV_p0kfcjEdlFogPsw',
    appId: '1:569805089105:web:3ccb0c53ec3d7e41020b70',
    messagingSenderId: '569805089105',
    projectId: 'mangprojects',
    authDomain: 'mangprojects.firebaseapp.com',
    storageBucket: 'mangprojects.firebasestorage.app',
    measurementId: 'G-W6M4QVNFN3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdPIzj484bvYgbtMsGM1wVnnEVlzr8uD0',
    appId: '1:569805089105:android:e270c15bdcd988d0020b70',
    messagingSenderId: '569805089105',
    projectId: 'mangprojects',
    storageBucket: 'mangprojects.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1XinjY-mP9hEbjldD6vlRHMrsfkYr1Sk',
    appId: '1:569805089105:ios:5c66d3c3081a734c020b70',
    messagingSenderId: '569805089105',
    projectId: 'mangprojects',
    storageBucket: 'mangprojects.firebasestorage.app',
    iosBundleId: 'com.afaq.mangProjects',
  );
}
